apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../templates
nameSuffix: -deptusers-check-cached
patches:
  - target:
      kind: CronJob
      name: itassets-cronjob
    path: patch.yaml
  - target:
      kind: CronJob
      name: itassets-cronjob
    options:
      allowNameChange: true
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/name
        value: itassets-cronjob-check-departmentusers
