apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
resources:
  - ../../base
  - cronjobs/deptusers-check-ascender
  - ingress.yaml
  - postgres_fdw_pvc.yaml
secretGenerator:
  - name: itassets-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      variant: uat
patches:
  - path: clusterip_patch.yaml
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: pdb_patch.yaml
  - path: postgres_fdw_patch.yaml
